---
name: GitHub-hosted runners system info via GitHub Actions
on: [workflow_dispatch]
env:
  RUBY_VERSION: 3.1.1
  GIT_USER_EMAIL: blah+pakkun@cliffano.com
  GIT_USER_NAME: pakkunbot
  VERSIONS: 'ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-14, macos-13, macos-12, macos-11, windows-latest, windows-2022, windows-2019'
jobs:
  collect-data-ubuntu-macos:
    strategy:
      matrix:
        version: [ubuntu-24.04, ubuntu-24.04, ubuntu-20.04, macos-latest, macos-14, macos-13, macos-12, macos-11]
    runs-on: ${{ matrix.version }}
    steps:
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - run: gem install facter
      - run: facter --hocon > facter.hocon
      - run: facter --json > facter.json
      - run: facter --yaml > facter.yaml
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.version }}
          path: ./
          retention-days: 1
          compression-level: 0
  collect-data-windows:
    strategy:
      matrix:
        version: [windows-latest, windows-2022, windows-2019]
    runs-on: ${{ matrix.version }}
    steps:
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - run: gem install ffi facter
      - run: facter --hocon | Out-File facter.hocon
      - run: facter --json | Out-File facter.json
      - run: facter --yaml | Out-File facter.yaml
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.version }}
          path: ./
          retention-days: 1
          compression-level: 0
  consolidate-data:
    needs:
      - collect-data-ubuntu-macos
      - collect-data-windows
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          set-safe-directory: ${{ github.workspace }}
      - uses: cliffano/command-loop-action@main
        with:
          items: ${{ env.VERSIONS }}
          command: 'rm -rf data/github-actions-github-hosted-runners/rockylinux-$ITEM/*'
      - run: mkdir -p data/github-actions-github-hosted-runners
      - uses: actions/download-artifact@master
        with:
          path: data/github-actions-github-hosted-runners
      - run: git config --global user.email "${{ env.GIT_USER_EMAIL }}"
      - run: git config --global user.name "${{ env.GIT_USER_NAME }}"
      - run: git add -A
      - run: git status
      - uses: cliffano/command-loop-action@main
        with:
          items: ${{ env.VERSIONS }}
          command: 'git commit data/github-actions-github-hosted-runners/$ITEM/* -m "Update data for GitHub Actions $ITEM via GitHub Actions."'
      - run: git pull --rebase
      - uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
